# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6c2187c4bbf5dc6420f4acd2a221195896a3a7e258dcab2353797223d8df988105898c6d926233f1bfa4b34710a735f6559c306c2ea14a83587bb5360e747a8

test:
  secret_key_base: 939f4287e3df2540f385ab049543e499a5f5764bdadcc6b002581e206e8ef1f6be1cf7d6a4b8b205e9220c40eb45f3f4352169269a7f1398d41b2f15d3b0ef2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
